CREATE DATABASE Agile
GO

USE Agile
GO

CREATE TABLE Users(
	UserId CHAR(5) PRIMARY KEY,
	UserName VARCHAR (150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Password VARCHAR(150) NOT NULL,
	NoTelp VARCHAR(15) NOT NULL,
	Gender VARCHAR(6) NOT NULL
);
--DROP TABLE Users