CREATE DATABASE Agile;

USE Agile;

CREATE TABLE Users(
	UserId CHAR(5) PRIMARY KEY,
	UserName VARCHAR (150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Password VARCHAR(150) NOT NULL,
	NoTelp VARCHAR(15) NOT NULL,
	Gender CHAR(1) NOT NULL,
	DisplayPicture VARCHAR(150)
);
-- DROP TABLE Users
